#!/bin/bash

set -e
set -o pipefail

indent() {
	sed -u 's/^/       /'
}

echo "-----> Starting the all-in-one OpenProject setup at $BASH_SOURCE..."

if [ "$PGDATA" == "" ]; then
	echo "No PGDATA environment variable defined. Aborting." | indent
	exit 2
fi

PG_STARTUP_WAIT_TIME=${PG_STARTUP_WAIT_TIME:=1000}
SUPERVISORD_LOG_LEVEL=${SUPERVISORD_LOG_LEVEL:=info}

PLUGIN_GEMFILE_TMP=$(mktemp)
PLUGIN_GEMFILE=$APP_PATH/Gemfile.local

if [ "$PLUGIN_GEMFILE_URL" != "" ]; then
	echo "Fetching custom gemfile from ${PLUGIN_GEMFILE_URL}..."
	curl -L -o "$PLUGIN_GEMFILE_TMP" "$PLUGIN_GEMFILE_URL"

	# set custom plugin gemfile if file is readable and non-empty
	if [ -s "$PLUGIN_GEMFILE_TMP" ]; then
		mv "$PLUGIN_GEMFILE_TMP" "$PLUGIN_GEMFILE"
		chown $APP_USER:$APP_USER "$PLUGIN_GEMFILE"
	fi
fi

install_plugins() {
	pushd $APP_PATH >/dev/null

	if [ -s "$PLUGIN_GEMFILE" ]; then
		echo "Installing plugins..."
		bundle install

		echo "Installing frontend dependencies..."
		pushd $APP_PATH/frontend >/dev/null
		if [ "$(id -u)" = '0' ]; then
			su - $APP_USER -c "cd $APP_PATH/frontend && npm install"
		else
			npm install
		fi
		popd >/dev/null

		echo "Precompiling new assets..."
		bundle exec rake assets:precompile

		echo "Plugins installed"
	fi

	popd >/dev/null
}

migrate() {
	wait_for_postgres
	pushd $APP_PATH >/dev/null
	/etc/init.d/memcached start
	bundle exec rake db:migrate db:seed db:structure:dump
	/etc/init.d/memcached stop
	chown "$APP_USER.$APP_USER" db/structure.sql
	popd >/dev/null
}

wait_for_postgres() {
	retries=${PG_STARTUP_WAIT_TIME}

	echo "Trying to contact PostgreSQL server instance or waiting for it to come online."

	until psql $DATABASE_URL -c 'select 1;' > /dev/null 2>&1 || [ $retries -eq 0 ]; do
		echo "Waiting for postgres server, $((retries--)) remaining attempts..."
		sleep 3
	done
}

echo "-----> You're using an external database. Not initializing a local database cluster."
migrate | indent

echo "-----> Database setup finished."
echo "       On first installation, the default admin credentials are login: admin, password: admin"

echo "-----> Launching supervisord..."
exec /usr/bin/supervisord -c $APP_PATH/docker/supervisord.conf -e ${SUPERVISORD_LOG_LEVEL}
